language: python
dist: xenial
sudo: false
evn:
  global:
    - CAMPFIRE_TOKEN=FxQsoberKXawRGE7NtUYRA
    - TIMEOUT=1000
  matrix:
    - USE_NETWORK: true
python:
  - "3.7"
install:
  - "pip install -r requirements.txt"
script:
  - python3 main.py
